# Generated by Django 4.2.7 on 2024-06-26 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roca_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('diametro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roca_app.diametro')),
            ],
        ),
    ]
