# Generated by Django 4.2.7 on 2024-06-26 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roca_app', '0002_roller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho_inicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ancho_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alto_inicial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('alto_final', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='roca_app.roller')),
            ],
        ),
    ]
