# Generated by Django 4.2.7 on 2024-06-26 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roca_app', '0007_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roca_app.cliente')),
                ('usuario_generador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_instalacion_motor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_instalacion_roller', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_instalacion_cenefa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('cenefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roca_app.cenefa')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roca_app.cliente')),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roca_app.control')),
                ('diametro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roca_app.diametro')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roca_app.gateway')),
                ('motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='roca_app.motor')),
                ('roller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roca_app.roller')),
            ],
        ),
    ]
