# Generated by Django 4.2.7 on 2024-06-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roca_app', '0009_detallecotizacion_resumen_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
