# Generated by Django 4.2.7 on 2024-06-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roca_app', '0010_detallecotizacion_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumencotizacion',
            name='cotizacion_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
